Fix JVM options quoting in gradlew script
Removed extra quotes from DEFAULT_JVM_OPTS that were causing the
shell to pass quoted strings to Java, resulting in:
  Error: Could not find or load main class "-Xmx64m"

Changed from: DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'
Changed to:   DEFAULT_JVM_OPTS="-Xmx64m -Xms64m"

This allows the JVM options to be properly parsed when passed to
the java command.